#!/bin/bash
# Nova SessionStart Hook — NOVA-STATE.md 자동 생성 (cold-start, schema v2.0)
# 세션 시작 시 NOVA-STATE.md가 없으면 프로젝트 상태를 스캔하여 v2 포맷으로 자동 생성한다.
# Spec: docs/specs/nova-state-schema-v2.md

set -euo pipefail

# ── NOVA_COEXIST=1 — 게이트만 모드: NOVA-STATE.md 자동생성 생략 ──
# 다른 "세션 소유형" 오케스트레이션 플러그인과 공존 시 Nova는 working tree에 자동 산출물을
# 만들지 않는다(생성물 0). 게이트(pre-commit-reminder.sh)는 .nova/ 존재(= /nova:review 1회
# 이상 실행)를 활성 기준으로 쓰므로 게이트 자체는 유지된다 — 깨끗한 레포는 첫 review 전까지 skip.
[ "${NOVA_COEXIST:-0}" = "1" ] && exit 0

# v5.38.1 hotfix 패턴 이식: inherited 빈 stdin은 EOF가 안 와 `cat`이 무한 대기(hang) →
# nonblocking read -t 로 전환. (참조: hooks/pre-tool-use-record.sh)
INPUT=""
if [[ ! -t 0 ]]; then
  if IFS= read -r -t 1 INPUT 2>/dev/null; then
    while IFS= read -r -t 0.1 _next 2>/dev/null; do
      INPUT="${INPUT}${_next}"
    done
  fi
fi
CWD=$(echo "$INPUT" | jq -r '.cwd // "."' 2>/dev/null || true)

# cwd 폴백
if [ -z "$CWD" ] || [ "$CWD" = "null" ] || [ "$CWD" = "." ]; then
  CWD="$(pwd)"
fi

# CWD 경로 검증: 절대경로 확인 + 디렉토리 존재 확인
case "$CWD" in
  /*) ;;
  *) exit 0 ;;
esac

if [ ! -d "$CWD" ]; then
  exit 0
fi

# 프로젝트 정보 수집 (set +e로 find 실패 허용 — docs/ 없는 프로젝트 대응)
set +e
PLAN_COUNT=$(find "$CWD/docs/plans" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
DESIGN_COUNT=$(find "$CWD/docs/designs" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
VERIFY_COUNT=$(find "$CWD/docs/verifications" -maxdepth 1 -name "*.md" 2>/dev/null | wc -l | tr -d ' ')
set -e

PLAN_REF="none"
DESIGN_REF="none"
VERIFY_REF="none"

if [ "${PLAN_COUNT:-0}" -gt 0 ]; then
  PLAN_REF=$(find "$CWD/docs/plans" -maxdepth 1 -name "*.md" 2>/dev/null | head -1 | sed "s|$CWD/||")
fi
if [ "${DESIGN_COUNT:-0}" -gt 0 ]; then
  DESIGN_REF=$(find "$CWD/docs/designs" -maxdepth 1 -name "*.md" 2>/dev/null | head -1 | sed "s|$CWD/||")
fi
if [ "${VERIFY_COUNT:-0}" -gt 0 ]; then
  VERIFY_REF=$(find "$CWD/docs/verifications" -maxdepth 1 -name "*.md" 2>/dev/null | sort | tail -1 | sed "s|$CWD/||")
fi

TODAY=$(date +%Y-%m-%d)

# NOVA-STATE.md 원자적 생성 (noclobber로 TOCTOU 경쟁 조건 해소)
# 이미 존재하면 자동 실패 → exit 0
set -C
{
# ── Frontmatter (정형 SoT, 기계 권위) ──────────────────────────
printf -- '---\n'
printf 'schema_version: 2\n'
printf 'goal: "(CLAUDE.md 기반 초기화 필요 — /nova:next 실행 또는 frontmatter 직접 수정)"\n'
printf 'active_ao: null\n'
printf 'handoff: null\n'
printf -- '---\n'
printf '\n'

# ── 본문 (사람 가독, 마크다운 뷰어 친화) ────────────────────────
printf '# 🚀 Nova State\n'
printf '\n'

printf '## 🎯 Current\n'
printf '**(초기화 필요)** — `/nova:next` 실행 또는 frontmatter `goal` 직접 수정\n'
printf '\n'
printf '> [!NOTE]\n'
printf '> **다음 행동**: 프로젝트 첫 진입. `/nova:next`로 작업 시작 또는 CLAUDE.md 기반 goal 수동 설정.\n'
printf '\n'

printf '## 🌳 Active Tree\n'
printf '\n'
printf '> 진행 중인 AO 없음. 새 작업 시작 시 여기에 트리가 그려짐.\n'
printf '\n'

printf '## 📊 Recent Activity\n'
printf '\n'
printf '| 시각 | 작업 | 결과 |\n'
printf '|------|------|:----:|\n'
printf '| %s | /nova:init → NOVA-STATE.md 자동 생성 (cold-start) | ✅ |\n' "$TODAY"
printf '\n'

printf '## ⚠️ Risks & Gaps\n'
printf '\n'
printf '| 항목 | 심각도 | 상태 |\n'
printf '|------|:------:|------|\n'
printf '| — | — | — |\n'
printf '\n'

printf '## 🛡️ 규칙 우회 이력\n'
printf '\n'
printf '| 날짜 | 커맨드 | 우회 이유 | 사후 조치 |\n'
printf '|------|--------|----------|----------|\n'
printf '| — | — | — | — |\n'
printf '\n'
printf '> `--emergency` 플래그 사용 또는 Evaluator 건너뛸 때 반드시 기록. 미기록 = Hard-Block.\n'
printf '\n'

printf '## 🔗 Refs\n'
printf -- '- **Plan**: %s\n' "$PLAN_REF"
printf -- '- **Design**: %s\n' "$DESIGN_REF"
printf -- '- **Last Verification**: %s\n' "$VERIFY_REF"
printf '\n'

printf -- '---\n'
printf '\n'
printf '<sub>📐 schema_version: 2 · Generated by Nova session-start (cold-start, %s)</sub>\n' "$TODAY"
} > "$CWD/NOVA-STATE.md" 2>/dev/null || exit 0

exit 0
